max_velocity: 2
max_acceleration: 1
resolution: 0.15
num_opt_points: "\x07"
step_size: 0.25
rrt_factor: 1.15
max_solve_t: 5
uav_radius: 0.7
num_iter: ˆ
num_pt_window: "\x04"
clear_distance: 1.2
max_check_dist: 2.5